apps/sklad/urls.py
from apps.sklad.views import *
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
app_name = 'sklad'
urlpatterns = [
    path('', StartSkladView.as_view(), name = 'start'),
    path('<int:id>/formaauto', StartSkladView.forma, name = 'formaauto'),
    path('/addagent', StartSkladView.addAgent, name = 'addagent'),
    path('addAgent', AddAgentView.as_view(), name='agentadd'),
    path('settings', Setting.as_view(), name='settings'),
]

apps/vesovay/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include

from apps.vesovay.views import *

app_name = 'vesovay'
urlpatterns = [
    path('', StartVesView.as_view(), name= 'start'),
    path('<int:error>/<nomer>/', StartVesView.by_error, name= 'by_erorr'),
    path('addCar', AddVesCarView.as_view(), name='addcar'),
    path('addTrain', AddVesTrainView.as_view(), name='addtrain'),
]

vzveshivanie/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include

from vzveshivanie import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('vesovay/', include('apps.vesovay.urls')),
    path('sklad/', include('apps.sklad.urls')),
    path('', views.redidrec, name = 'redirect'),
    url('accounts/', include('django.contrib.auth.urls')),
]

apps/sklad/models.py
from django.db import models

# Create your models here.

class Agent(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField('Наименование', max_length=255)
    description = models.TextField('Описание', default=None)
    address = models.TextField('Адрес', default=None)
    date_add = models.DateTimeField(auto_now_add=True)
    date_update = models.DateTimeField(auto_now=True)
    unp = models.BigIntegerField('УНП')
    def __str__(self):
        return self.name
    class Meta:
        verbose_name = 'Агент'
        verbose_name_plural = 'Агенты'

apps/sklad/views.py
from django.shortcuts import render
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import TemplateView, FormView
# Create your views here.
from apps.sklad.models import Agent
from apps.vesovay.models import Auto, Vagon
from setting_common import USER_ROLES_SETTINGS
from vzveshivanie.views import AbsView


class AbsAuthSkladView(AbsView):

    def _response_with_permissions(self, dispatch_response, request, *args, **kwargs):

        if not hasattr(dispatch_response, 'status_code') or dispatch_response.status_code == 302:
            return dispatch_response

        elif (not request.user or not request.user.client or (request.user.client.user_role == USER_ROLES_SETTINGS[0][0])or (request.user.client.user_role == USER_ROLES_SETTINGS[1][0])):
            return self.handle_no_permission()
        else:
            return dispatch_response

class AbsAuthAdminView(AbsView):

    def _response_with_permissions(self, dispatch_response, request, *args, **kwargs):

        if not hasattr(dispatch_response, 'status_code') or dispatch_response.status_code == 302:
            return dispatch_response

        elif (not request.user or not request.user.client or (request.user.client.user_role == USER_ROLES_SETTINGS[0][0]) or (request.user.client.user_role == USER_ROLES_SETTINGS[1][0]) or (request.user.client.user_role == USER_ROLES_SETTINGS[3][0])):
            return self.handle_no_permission()
        else:
            return dispatch_response


class StartSkladView(AbsAuthSkladView):

    template_name = 'sklad/index.html'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

    def get(self, request,**kwargs):
        auto = Auto.objects.all().order_by('id')
        vagon = Vagon.objects.all().order_by('id')
        context = {'auto': auto,'vagon':vagon}
        return render(request, self.template_name, context)

    def forma(request,id):
        auto = Auto.objects.filter(id=id)
        agent = Agent.objects.all().order_by('id')
        auto = auto[0]
        print(agent)
        context = {'auto': auto,'agent':agent}
        return render(request, 'sklad/forma.html', context)

    def addAgent(request):
        agent = Agent.objects.all().order_by('id')
        context = {'agents': agent}
        return render(request, 'sklad/addagent.html', context)

class AddAgentView(AbsAuthSkladView):
    template_name = 'sklad/addagent.html'

    def post(self, request, *args, **kwargs):
        form = self.request.POST
        address = form['address-city'] + ", " + form['address-street']
        ag = Agent(name = form['name'], address = address, unp= form['unp'], description=form['description'])
        ag.save()
        print(ag)
        return redirect('sklad:addagent')

class Setting(AbsAuthAdminView):
    template_name = 'setting.html'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

    def post(self, request, *args, **kwargs):
        context = {'agents': ''}
        return render(request, 'setting.html', context)

templates/sklad/addagent.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Агенты {% endblock %}
{% block where %} Агенты {% endblock %}


{% block content %}
    <link rel="stylesheet" href="{% static 'bootstrap/css/boot.css' %}">
    <link rel="stylesheet" href="{% static 'bootstrap/css/boottable.css' %}">
    <script src="{% static 'bootstrap/js/jq.js' %}"></script>
    <script src="{% static 'bootstrap/js/popper.js' %}"></script>
    <script src="{% static 'bootstrap/js/bmin.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootJsTable.js' %}"></script>


    <div class="container-fluid"
         style="padding: 0%;margin:0%;background-color: #000306; min-height: 85vh; color: white; ">

        <h3 style="color: white">Таблица контрагентов ||
            <button data-toggle="modal" data-target="#modalForm" class=" btn btn-success ">Добавить</button>
            ||| <a
                    href="{% url 'sklad:start' %}" class=" btn btn-primary ">назад</a></h3>
        </h3>
        <table data-toggle="table" data-pagination="true" data-search="true" style="color: white; text-align: center;">
            <thead>
            <tr>
                <th rowspan="2" data-sortable="true" data-field="id">id</th>
                <th colspan="4">огранизация</th>
                <th rowspan="2">Адрес</th>
                <th rowspan="2">Описание</th>
            </tr>
            <tr>
                <th data-sortable="true">УНП</th>
                <th data-sortable="true">название</th>
                <th data-sortable="true">добавлена</th>
                <th data-sortable="true">обновлена</th>
            </tr>
            </thead>
            <tbody>
            {% for a in agents %}
                <tr>
                    <td>{{ a.id }}</td>
                    <td>{{ a.unp }}</td>
                    <td>{{ a.name }}</td>
                    <td>{{ a.date_add }}</td>
                    <td>{{ a.date_update }}</td>
                    <td>{{ a.address }}</td>
                    <td>{{ a.description }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

        <!--=================================================================================================== -->
        <!-- Modal -->
        <div class="modal fade" id="modalForm" tabindex="-1" role="dialog" aria-labelledby="modalForm"
             aria-hidden="true" style="color: black">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h4 class="modal-title" id="modalForm">Добавление контрагента</h4>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <form action="{% url 'sklad:agentadd' %}" method="post">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="name">Название</label>
                                <input type="text" class="form-control" id="name" name="name"
                                       placeholder="ООО МВЛАБ " required>
                            </div>
                            <div class="form-group">
                                <label for="unp">УНП</label>
                                <input type="number" class="form-control" id="unp" name="unp"
                                       placeholder="46456743456 " >
                            </div>
                            <div class="form-group">
                                <label for="address-city">Город</label>
                                <input type="text" class="form-control" id="address-city" name="address-city"
                                       placeholder="Минск" required>
                            </div>
                            <div class="form-group">
                                <label for="address-street">улица/переулок</label>
                                <input type="text" class="form-control" id="address-street" name="address-street"
                                       placeholder="Железнодорожная 27В " required>
                            </div>
                            <div class="form-group">
                                <label for="description">описание</label>
                                <textarea type="text" class="form-control" id="description" name="description"
                                          placeholder="компания разработчик программного обеспечения "></textarea>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">отмена</button>
                                <button type="submit" class="btn btn-primary">Добавить</button>
                            </div>
                        </form>
                    </div>

                </div>
            </div>
        </div>
        <!--=================================================================================================== -->

    </div>

{% endblock %}

templates/sklad/forma.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Склад | Форма {% endblock %}
{% block where %} заполнение агента {% endblock %}


{% block content %}
    <div class="container-fluid"
         style="padding: 0%;margin:0%;background-color: #000306; min-height: 85vh; color: white; ">
        <h3>Заполнение контрагента для автотранспорта | <a href="{% url 'sklad:start' %}"
                                                           class="btn btn-primary">НАЗАД</a></h3>
        <div class="row">
            <div class="col-sm">
                <h4>Госномер: {{ auto.number }}</h4>
                <h4>Номер накладной: {{ auto.nakladnaya }} </h4>
                <h4>дата и время въезда: {{ auto.last_in }}</h4>
                <h4>дата и время выезда: {{ auto.last_out }}</h4>
                <h4>Вес на въезде: {{ auto.ves_in }} кг</h4>
                <h4>Вес на выезде: {{ auto.ves_out }} кг</h4>
                <h4>Нетто: {{ auto.netto_last }} кг</h4>
            </div>
            <div class="col-sm">
                <form>
                    {% csrf_token %}
                    <div class="form-group ">
                        <label class="d-block" for="fname">Фамилия водителя</label>
                        <input onkeyup="valid(this)" type="text" class="form-control d-inline" id="fname" name="fname"
                               style="width: 80%;"
                               placeholder="Петров" required> <span id="fname_sp" class="badge badge-danger d-inline">X</span>
                    </div>
                    <div class="form-group">
                        <label class="d-block" for="Nplist">Номер путевого листа</label>
                        <input onkeyup="valid(this)" type="number" class="form-control d-inline" id="Nplist"
                               name="Nplist" style="width: 80%;"
                               placeholder="6545674" required> <span id="Nplist_sp" class="badge badge-danger d-inline">X</span>
                    </div>
                    <div class="form-group ">
                        <label class="d-block" for="naklad">Накладная</label>
                        <input onkeyup="valid(this)" type="number" class="form-control d-inline" id="naklad"
                                {% if auto.nakladnaya %} value="{{ auto.nakladnaya }}" {% endif %} name="naklad"
                               style="width: 80%;"
                               placeholder="05943684" required> <span id="naklad_sp" class="badge badge-danger d-inline">X</span>
                    </div>
                <div class="form-group ">
                        <label class="d-block" for="naklad">Контрагент</label>
                        <select  type="number" class="form-control d-inline" id="agent"
                               name="agent"
                               style="width: 80%;"
                                required>
                         <option value="0" selected disabled> Выберите контрагента</option>
                            {% for ag in agent %}
                            <option value="{{ ag.id }}"> {{ ag.name }} </option>
                            {% endfor %}
                        </select>
                            <span id="agent_sp" class="badge badge-danger d-inline">X</span>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <script>
    function valid(event) {
            //switch (event.id) {
              //  case "fname":
                    if(event.value.length>2){
                        $("#"+event.id+"_sp").removeClass('badge-danger');
                        $("#"+event.id+"_sp").addClass('badge-success');
                        $("#"+event.id+"_sp").html("V");
                    }else{
                         $("#"+event.id+"_sp").removeClass('badge-success ');
                        $("#"+event.id+"_sp").addClass('badge-danger');
                        $("#"+event.id+"_sp").html('X');
                    }
                 //   break;
         //   }
    }
    </script>
{% endblock %}

templates/sklad/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Склад {% endblock %}
{% block where %} Склад {% endblock %}


{% block content %}
<link rel="stylesheet" href="{% static 'bootstrap/css/boot.css' %}" >
    <link rel="stylesheet" href="{% static 'bootstrap/css/boottable.css' %}" >
    <script src="{% static 'bootstrap/js/jq.js' %}" ></script>
<script src="{% static 'bootstrap/js/popper.js' %}"  ></script>
<script src="{% static 'bootstrap/js/bmin.js' %}"></script>
     <script src="{% static 'bootstrap/js/bootJsTable.js' %}" ></script>
<div class="container-fluid" style="padding: 0%;margin:0%;background-color: #000306; min-height: 85vh; color: white; ">
<ul class="nav nav-tabs" style="background-color: #000306; "  >
  <li lass="nav-item"><a class="nav-link active"  data-toggle="tab" href="#panel1">Транспорт с автомобильных весов</a></li>
  <li lass="nav-item"><a  class="nav-link" data-toggle="tab" href="#panel2">Транспорт с железнодорожных весов</a></li>
<a href="{% url 'sklad:addagent' %}" class=" btn btn-primary " style="float: right; margin-left: 20%;" >Добавить контрагента</a>
</ul>

<div class="tab-content">
      <div id="panel1" class="tab-pane active" >
        <h3 style="color: white">Таблица автотранспорта</h3>
      <table data-toggle="table" data-pagination="true" data-search="true" style="color: white; text-align: center;">
              <thead>
            <tr>
                <th rowspan="2" data-sortable="true" data-field="id">id</th>
                <th rowspan="2" >номер</th>
                <th rowspan="2" >контрагент</th>
                <th colspan="2">Время</th>
                 <th colspan="3">Вес, кг</th>
                <th rowspan="2">На территории?</th>
                <th rowspan="2">обработан?</th>
            </tr>
            <tr>
                <th data-sortable="true">въезд</th>
                <th data-sortable="true">выезд</th>
                <th data-sortable="true">въезд</th>
                <th data-sortable="true">выезд</th>
                 <th data-sortable="true">нетто</th>
            </tr>
        </thead>
        <tbody>
              {% for a in auto %}
                  <tr>
        <td >{{ a.id }}</td>
         <td><a href="{% url 'sklad:formaauto' a.id %}" {% if a.status_in %} class="btn btn-danger disabled" {% else %}class="btn btn-success" {% endif %}>{{ a.number }}</a></td>
         <td></td>
        <td  >{{ a.last_in }}</td>
        <td >{% if a.last_out %} {{ a.last_out }}{% else %} не выезжал {% endif %}</td>
        <td >{{ a.ves_in }}</td>
        <td >{{ a.ves_out }}</td>
        <td >{{ a.netto_last }}</td>
         <td>{% if a.status_in %}<span class="badge badge-danger" style="width: 100%;">да</span>{% else %}<span class="badge badge-success" style="width: 100%;">нет</span> {% endif %}</td>
                  <td> <span class="badge badge-danger" style="width: 100%;">НЕТ</span></td>
                  </tr>
              {% endfor %}
        </tbody>
      </table>
          <form style="color: white;" action="{% url 'vesovay:addcar' %}" method="post">
                  {% csrf_token %}
          </form>
      </div>
     <div id="panel2" class="tab-pane" >
        <h3 style="color: white">Таблица ЖД транспорта</h3>

         <table data-toggle="table" data-pagination="true" data-search="true" style="color: white; text-align: center;">
              <thead>
            <tr>
                <th rowspan="2" data-sortable="true" data-field="id">id</th>
                <th rowspan="2" >номер</th>
                <th rowspan="2" >контрагент</th>
                <th colspan="2">Время</th>
                 <th colspan="3">Вес, кг</th>
                <th rowspan="2">На территории?</th>
                <th rowspan="2">обработан?</th>
            </tr>
            <tr>
                <th data-sortable="true">въезд</th>
                <th data-sortable="true">выезд</th>
                <th data-sortable="true">въезд</th>
                <th data-sortable="true">выезд</th>
                 <th data-sortable="true">нетто</th>
            </tr>
        </thead>
        <tbody>
              {% for a in vagon %}
                  <tr>
        <td >{{ a.id }}</td>
         <td><a href="{% url 'sklad:formaauto' a.id %}" {% if a.status_in %} class="btn btn-danger disabled" {% else %}class="btn btn-success" {% endif %}>{{ a.number }}</a></td>
         <td></td>
        <td  >{{ a.last_in }}</td>
        <td >{% if a.last_out %} {{ a.last_out }}{% else %} не выезжал {% endif %}</td>
        <td >{{ a.ves_in }}</td>
        <td >{{ a.ves_out }}</td>
        <td >{{ a.netto_last }}</td>
         <td>{% if a.status_in %}<span class="badge badge-danger" style="width: 100%;">да</span>{% else %}<span class="badge badge-success" style="width: 100%;">нет</span> {% endif %}</td>
                  <td> <span class="badge badge-danger" style="width: 100%;">НЕТ</span></td>
                  </tr>
              {% endfor %}
        </tbody>
      </table>





         <form  action="{% url 'vesovay:addcar' %}" method="post">
                  {% csrf_token %}
          </form>
      </div>
</div>
</div>





{% endblock %}