apps/sklad/urls.py
from apps.sklad.views import *
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
app_name = 'sklad'
urlpatterns = [
    path('', StartSkladView.as_view(), name = 'start'),
    path('<int:id>/formaauto', StartSkladView.forma, name = 'formaauto'),
    path('/addagent', StartSkladView.addAgent, name = 'addagent'),
    path('addAgent', AddAgentView.as_view(), name='agentadd'),
    path('settings', Setting.as_view(), name='settings'),
]

apps/vesovay/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include

from apps.vesovay.views import *

app_name = 'vesovay'
urlpatterns = [
    path('', StartVesView.as_view(), name= 'start'),
    path('<int:error>/<nomer>/', StartVesView.by_error, name= 'by_erorr'),
    path('addCar', AddVesCarView.as_view(), name='addcar'),
    path('addTrain', AddVesTrainView.as_view(), name='addtrain'),
]

vzveshivanie/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include

from vzveshivanie import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('vesovay/', include('apps.vesovay.urls')),
    path('sklad/', include('apps.sklad.urls')),
    path('', views.redidrec, name = 'redirect'),
    url('accounts/', include('django.contrib.auth.urls')),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %} | MVLab</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="stylesheet" href="{% static 'bootstrap/css/boot.css' %}" >
</head>

<body link="white";">
<header class="shap" role="banner" >
    <div class="container-fluid">
        <div class="row"  style="color: white;">
            <div class="col-md-3 logotip" style="color: white;">
                <a href="/"><img style="margin: 2%;" src="{% static  'img/logo.png' %}" alt="mvlab.by"></a>
            </div>

            <div class="col-md-5"></div>
            <div class="col-md-4 ">
              <div class="row">

                <div class="col-4" id="statusConnect">
                <span class="badge badge-warning" style="width: 100%;">Подключение к Server</span>
                    </div>
                  <div class="col-3" id="statusConnectPlc1">
                <span class="badge badge-danger" style="width: 100%;">PLC1</span>
                    </div>
                  <div class="col-3" id="statusConnectPlc2" >
                <span class="badge badge-danger" style="width: 100%;">PLC2</span>
                    </div>
                   <div class="col-2">
                <a class="btn btn-warning" href="{% url 'logout' %}"> Выйти</a>
                    </div>
                </div>
                </div>


            <div class="col-md-5" style="margin-bottom: 1%;"> <h3>Система учета || {% block where %}{% endblock %} </h3>
            {% if request.user.client.user_role == "admin"   %}
                <a  class="btn btn-primary" href="{% url 'vesovay:start' %}">Взвешивание</a>
                <a  class="btn btn-primary" href="{% url 'sklad:start' %}">Склад</a>
                <a  class="btn btn-primary" href="{% url 'sklad:settings' %}">Настройки</a>
            {% endif %}
            </div>
            <div class="col-md-7 top-add"> <h3>Пользователь :  {{ request.user.username }}</h3><h5>Роль :  {{ request.user.client.user_role }}</h5></div>
        </div>
    </div>
</header>
{% block content %}
{% endblock %}
<script src="{% static 'bootstrap/js/jq.js' %}" ></script>
<script src="{% static 'bootstrap/js/popper.js' %}"  ></script>
<script src="{% static 'bootstrap/js/bmin.js' %}"></script>
</body>
</html>


<style>
    img{max-width:100%;height:auto}
.logotip img{max-height:90px;width:auto}
@media (min-width: 768px) {
.top-add{text-align: right}
}
@media (max-width: 767px) {
.logotip{text-align: center;margin-bottom: 10px}
}
    .shap{
        background-color: #000913;
        margin-top: 0%;
    }

.disabledB{
  pointer-events: none;

  /* for "disabled" effect */
  opacity: 0.5;
  background: #CCC;
}
    .disabled{
  pointer-events: none;

  /* for "disabled" effect */
  opacity: 0.5;
  background: #ffffff;
}
</style>




<script>
    var timer ;
    var roomName = 'wert';
    var chatSocketClose=false;
    var chatSocketCOpen=false;
    var chatSocket;
function connectBase() {

if(!chatSocketCOpen){
                    chatSocket = new WebSocket(
                     'ws://' + window.location.host + '/ws/');
}
  chatSocket.onopen = function() {
             chatSocketCOpen= true;
             chatSocketClose=false;
             $("#statusConnect").html('<span class="badge badge-success" style="width: 100%;">OnLINE Server</span>');
             $("#noconnectError").hide();
             $("#for_disabled1").removeClass('disabledB');
             $("#for_disabled2").removeClass('disabledB');
             clearInterval(timer);
               };
    chatSocket.onmessage = function(e) {
        var data = JSON.parse(e.data);
        var message = data['message'];
        document.querySelector('#chat-log').value += (message + '\n');
        alert('new message');
    };

    chatSocket.onclose = function(e) {
        console.error('Chat socket closed unexpectedly');
        chatSocketClose=true;
        $("#statusConnect").html('<span class="badge badge-danger" style="width: 100%;">OFFLINE Server</span>');
        $("#noconnectError").show();
        $("#for_disabled1").addClass('disabledB');
        $("#for_disabled2").addClass('disabledB');
        if (chatSocketCOpen){
            reconnectTimer();
        }

         chatSocketCOpen= false;
    };
    {##}
    {#document.querySelector('#chat-message-input').focus();#}
    {#document.querySelector('#chat-message-input').onkeyup = function(e) {#}
    {#    if (e.keyCode === 13) {  // enter, return#}
    {#        document.querySelector('#chat-message-submit').click();#}
    {#    }#}
    {#};#}
    {##}
    {#document.querySelector('#chat-message-submit').onclick = function(e) {#}
    {#    var messageInputDom = document.querySelector('#chat-message-input');#}
    {#    var message = messageInputDom.value;#}
    {#    chatSocket.send(JSON.stringify({#}
    {#        'message': message#}
    {#    }));#}
    {##}
    {#    messageInputDom.value = '';#}
    {#};#}


    }

function reconnectTimer() {
     timer = setInterval (reconnect, 1000);
}

  function reconnect() {
        connectBase();
         $('#element').toast('show');
    }


connectBase();
</script>

templates/setting.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Настройки {% endblock %}
{% block where %} Настройки {% endblock %}

{% block content %}

settings

{% endblock %}